### YamlMime:ManagedReference
items:
- uid: ESAPIX.AppKit.Data.AppSettings
  commentId: T:ESAPIX.AppKit.Data.AppSettings
  id: AppSettings
  parent: ESAPIX.AppKit.Data
  children:
  - ESAPIX.AppKit.Data.AppSettings.Get``1(System.String)
  - ESAPIX.AppKit.Data.AppSettings.Load(System.String)
  - ESAPIX.AppKit.Data.AppSettings.Save(System.String)
  - ESAPIX.AppKit.Data.AppSettings.Set(System.String,System.Object)
  - ESAPIX.AppKit.Data.AppSettings.Settings
  langs:
  - csharp
  - vb
  name: AppSettings
  nameWithType: AppSettings
  fullName: ESAPIX.AppKit.Data.AppSettings
  type: Class
  source:
    id: AppSettings
    path: ''
    startLine: 904
  assemblies:
  - cs.temp.dll
  namespace: ESAPIX.AppKit.Data
  syntax:
    content: public class AppSettings
    content.vb: Public Class AppSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: ESAPIX.AppKit.Data.AppSettings.Settings
  commentId: P:ESAPIX.AppKit.Data.AppSettings.Settings
  id: Settings
  parent: ESAPIX.AppKit.Data.AppSettings
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: AppSettings.Settings
  fullName: ESAPIX.AppKit.Data.AppSettings.Settings
  type: Property
  source:
    id: Settings
    path: ''
    startLine: 906
  assemblies:
  - cs.temp.dll
  namespace: ESAPIX.AppKit.Data
  syntax:
    content: public Dictionary<string, object> Settings { get; set; }
    content.vb: Public Property Settings As Dictionary(Of String, Object)
    parameters: []
    return:
      type: Dictionary{System.String,System.Object}
  overload: ESAPIX.AppKit.Data.AppSettings.Settings*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: ESAPIX.AppKit.Data.AppSettings.Load(System.String)
  commentId: M:ESAPIX.AppKit.Data.AppSettings.Load(System.String)
  id: Load(System.String)
  parent: ESAPIX.AppKit.Data.AppSettings
  langs:
  - csharp
  - vb
  name: Load(String)
  nameWithType: AppSettings.Load(String)
  fullName: ESAPIX.AppKit.Data.AppSettings.Load(System.String)
  type: Method
  source:
    id: Load
    path: ''
    startLine: 908
  assemblies:
  - cs.temp.dll
  namespace: ESAPIX.AppKit.Data
  syntax:
    content: public static AppSettings Load(string settingsPath = "")
    content.vb: Public Shared Function Load(settingsPath As String = "") As AppSettings
    parameters:
    - id: settingsPath
      type: System.String
    return:
      type: ESAPIX.AppKit.Data.AppSettings
  overload: ESAPIX.AppKit.Data.AppSettings.Load*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: ESAPIX.AppKit.Data.AppSettings.Save(System.String)
  commentId: M:ESAPIX.AppKit.Data.AppSettings.Save(System.String)
  id: Save(System.String)
  parent: ESAPIX.AppKit.Data.AppSettings
  langs:
  - csharp
  - vb
  name: Save(String)
  nameWithType: AppSettings.Save(String)
  fullName: ESAPIX.AppKit.Data.AppSettings.Save(System.String)
  type: Method
  source:
    id: Save
    path: ''
    startLine: 919
  assemblies:
  - cs.temp.dll
  namespace: ESAPIX.AppKit.Data
  syntax:
    content: public bool Save(string settingsPath = "")
    content.vb: Public Function Save(settingsPath As String = "") As Boolean
    parameters:
    - id: settingsPath
      type: System.String
    return:
      type: System.Boolean
  overload: ESAPIX.AppKit.Data.AppSettings.Save*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: ESAPIX.AppKit.Data.AppSettings.Get``1(System.String)
  commentId: M:ESAPIX.AppKit.Data.AppSettings.Get``1(System.String)
  id: Get``1(System.String)
  parent: ESAPIX.AppKit.Data.AppSettings
  langs:
  - csharp
  - vb
  name: Get<T>(String)
  nameWithType: AppSettings.Get<T>(String)
  fullName: ESAPIX.AppKit.Data.AppSettings.Get<T>(System.String)
  type: Method
  source:
    id: Get
    path: ''
    startLine: 936
  assemblies:
  - cs.temp.dll
  namespace: ESAPIX.AppKit.Data
  syntax:
    content: public T Get<T>(string key)
    content.vb: Public Function Get(Of T)(key As String) As T
    parameters:
    - id: key
      type: System.String
    typeParameters:
    - id: T
    return:
      type: '{T}'
  overload: ESAPIX.AppKit.Data.AppSettings.Get*
  nameWithType.vb: AppSettings.Get(Of T)(String)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: ESAPIX.AppKit.Data.AppSettings.Get(Of T)(System.String)
  name.vb: Get(Of T)(String)
- uid: ESAPIX.AppKit.Data.AppSettings.Set(System.String,System.Object)
  commentId: M:ESAPIX.AppKit.Data.AppSettings.Set(System.String,System.Object)
  id: Set(System.String,System.Object)
  parent: ESAPIX.AppKit.Data.AppSettings
  langs:
  - csharp
  - vb
  name: Set(String, Object)
  nameWithType: AppSettings.Set(String, Object)
  fullName: ESAPIX.AppKit.Data.AppSettings.Set(System.String, System.Object)
  type: Method
  source:
    id: Set
    path: ''
    startLine: 946
  assemblies:
  - cs.temp.dll
  namespace: ESAPIX.AppKit.Data
  syntax:
    content: public void Set(string key, object value)
    content.vb: Public Sub Set(key As String, value As Object)
    parameters:
    - id: key
      type: System.String
    - id: value
      type: System.Object
  overload: ESAPIX.AppKit.Data.AppSettings.Set*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: ESAPIX.AppKit.Data
  commentId: N:ESAPIX.AppKit.Data
  isExternal: false
  name: ESAPIX.AppKit.Data
  nameWithType: ESAPIX.AppKit.Data
  fullName: ESAPIX.AppKit.Data
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: ESAPIX.AppKit.Data.AppSettings.Settings*
  commentId: Overload:ESAPIX.AppKit.Data.AppSettings.Settings
  isExternal: false
  name: Settings
  nameWithType: AppSettings.Settings
  fullName: ESAPIX.AppKit.Data.AppSettings.Settings
- uid: Dictionary{System.String,System.Object}
  commentId: '!:Dictionary{System.String,System.Object}'
  definition: Dictionary`2
  name: Dictionary<String, Object>
  nameWithType: Dictionary<String, Object>
  fullName: Dictionary<System.String, System.Object>
  nameWithType.vb: Dictionary(Of String, Object)
  fullName.vb: Dictionary(Of System.String, System.Object)
  name.vb: Dictionary(Of String, Object)
  spec.csharp:
  - uid: Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: Dictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: Dictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Dictionary`2
  isExternal: true
  name: Dictionary<, >
  nameWithType: Dictionary<, >
  fullName: Dictionary<, >
  nameWithType.vb: Dictionary(Of , )
  fullName.vb: Dictionary(Of , )
  name.vb: Dictionary(Of , )
  spec.csharp:
  - uid: Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: Dictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: Dictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: ESAPIX.AppKit.Data.AppSettings.Load*
  commentId: Overload:ESAPIX.AppKit.Data.AppSettings.Load
  isExternal: false
  name: Load
  nameWithType: AppSettings.Load
  fullName: ESAPIX.AppKit.Data.AppSettings.Load
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: ESAPIX.AppKit.Data.AppSettings
  commentId: T:ESAPIX.AppKit.Data.AppSettings
  parent: ESAPIX.AppKit.Data
  isExternal: false
  name: AppSettings
  nameWithType: AppSettings
  fullName: ESAPIX.AppKit.Data.AppSettings
- uid: ESAPIX.AppKit.Data.AppSettings.Save*
  commentId: Overload:ESAPIX.AppKit.Data.AppSettings.Save
  isExternal: false
  name: Save
  nameWithType: AppSettings.Save
  fullName: ESAPIX.AppKit.Data.AppSettings.Save
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: ESAPIX.AppKit.Data.AppSettings.Get*
  commentId: Overload:ESAPIX.AppKit.Data.AppSettings.Get
  isExternal: false
  name: Get
  nameWithType: AppSettings.Get
  fullName: ESAPIX.AppKit.Data.AppSettings.Get
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  isExternal: false
  name: T
  nameWithType: T
  fullName: T
- uid: ESAPIX.AppKit.Data.AppSettings.Set*
  commentId: Overload:ESAPIX.AppKit.Data.AppSettings.Set
  isExternal: false
  name: Set
  nameWithType: AppSettings.Set
  fullName: ESAPIX.AppKit.Data.AppSettings.Set
